[package]
name = "bevy-math-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
clap = { version = "4.5.4", features = ["derive"] }
gettext-ng = "0.4.1"
lazy_static = "1.4.0"
rand = "0.8.5"
